# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: discovery.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'discovery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64iscovery.proto\x12\tCS6381_MW\"8\n\x0eRegistrantInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\"h\n\x0bRegisterReq\x12\x1d\n\x04role\x18\x01 \x01(\x0e\x32\x0f.CS6381_MW.Role\x12\'\n\x04info\x18\x02 \x01(\x0b\x32\x19.CS6381_MW.RegistrantInfo\x12\x11\n\ttopiclist\x18\x03 \x03(\t\"A\n\x0cRegisterResp\x12!\n\x06status\x18\x01 \x01(\x0e\x32\x11.CS6381_MW.Status\x12\x0e\n\x06reason\x18\x02 \x01(\t\"\x0c\n\nIsReadyReq\"\x1d\n\x0bIsReadyResp\x12\x0e\n\x06status\x18\x01 \x01(\x08\"(\n\x13LookupPubByTopicReq\x12\x11\n\ttopiclist\x18\x01 \x03(\t\"\x16\n\x14LookupPubByTopicResp\"\xd4\x01\n\x0c\x44iscoveryReq\x12%\n\x08msg_type\x18\x01 \x01(\x0e\x32\x13.CS6381_MW.MsgTypes\x12.\n\x0cregister_req\x18\x02 \x01(\x0b\x32\x16.CS6381_MW.RegisterReqH\x00\x12,\n\x0bisready_req\x18\x03 \x01(\x0b\x32\x15.CS6381_MW.IsReadyReqH\x00\x12\x34\n\nlookup_req\x18\x04 \x01(\x0b\x32\x1e.CS6381_MW.LookupPubByTopicReqH\x00\x42\t\n\x07\x43ontent\"\xdb\x01\n\rDiscoveryResp\x12%\n\x08msg_type\x18\x01 \x01(\x0e\x32\x13.CS6381_MW.MsgTypes\x12\x30\n\rregister_resp\x18\x02 \x01(\x0b\x32\x17.CS6381_MW.RegisterRespH\x00\x12.\n\x0cisready_resp\x18\x03 \x01(\x0b\x32\x16.CS6381_MW.IsReadyRespH\x00\x12\x36\n\x0blookup_resp\x18\x04 \x01(\x0b\x32\x1f.CS6381_MW.LookupPubByTopicRespH\x00\x42\t\n\x07\x43ontent*P\n\x04Role\x12\x10\n\x0cROLE_UNKNOWN\x10\x00\x12\x12\n\x0eROLE_PUBLISHER\x10\x01\x12\x13\n\x0fROLE_SUBSCRIBER\x10\x02\x12\r\n\tROLE_BOTH\x10\x03*\\\n\x06Status\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n\x0eSTATUS_SUCCESS\x10\x01\x12\x12\n\x0eSTATUS_FAILURE\x10\x02\x12\x16\n\x12STATUS_CHECK_AGAIN\x10\x03*y\n\x08MsgTypes\x12\x10\n\x0cTYPE_UNKNOWN\x10\x00\x12\x11\n\rTYPE_REGISTER\x10\x01\x12\x10\n\x0cTYPE_ISREADY\x10\x02\x12\x1c\n\x18TYPE_LOOKUP_PUB_BY_TOPIC\x10\x03\x12\x18\n\x14TYPE_LOOKUP_ALL_PUBS\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'discovery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROLE']._serialized_start=809
  _globals['_ROLE']._serialized_end=889
  _globals['_STATUS']._serialized_start=891
  _globals['_STATUS']._serialized_end=983
  _globals['_MSGTYPES']._serialized_start=985
  _globals['_MSGTYPES']._serialized_end=1106
  _globals['_REGISTRANTINFO']._serialized_start=30
  _globals['_REGISTRANTINFO']._serialized_end=86
  _globals['_REGISTERREQ']._serialized_start=88
  _globals['_REGISTERREQ']._serialized_end=192
  _globals['_REGISTERRESP']._serialized_start=194
  _globals['_REGISTERRESP']._serialized_end=259
  _globals['_ISREADYREQ']._serialized_start=261
  _globals['_ISREADYREQ']._serialized_end=273
  _globals['_ISREADYRESP']._serialized_start=275
  _globals['_ISREADYRESP']._serialized_end=304
  _globals['_LOOKUPPUBBYTOPICREQ']._serialized_start=306
  _globals['_LOOKUPPUBBYTOPICREQ']._serialized_end=346
  _globals['_LOOKUPPUBBYTOPICRESP']._serialized_start=348
  _globals['_LOOKUPPUBBYTOPICRESP']._serialized_end=370
  _globals['_DISCOVERYREQ']._serialized_start=373
  _globals['_DISCOVERYREQ']._serialized_end=585
  _globals['_DISCOVERYRESP']._serialized_start=588
  _globals['_DISCOVERYRESP']._serialized_end=807
# @@protoc_insertion_point(module_scope)
